routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\ErrorController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\EventsController;
use App\Http\Controllers\UploadController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Webex\WebexAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';
//Route::get('/phpinfo', function(){return phpinfo();});
Route::middleware('set.locale')->group(function () {
    Route::middleware(['auth', 'verified'])->group(function () {
        Route::redirect('/home', '/');
        Route::get('/',  [EventsController::class, 'index'])->name('home');
        Route::get('/event/create', [EventsController::class, 'edit'])->name('event.create');
        Route::get('/event/all', [EventsController::class, 'indexAll'])->name('event.all');
        Route::get('/event/edit/{id}', [EventsController::class, 'edit'])->name('event.edit');
        Route::get('/event/view/{id}', [EventsController::class, 'view'])->name('event.view');
        Route::post('/event/store/{id}', [EventsController::class, 'store'])->name('event.store');
        Route::post('/event/join', [EventsController::class, 'joinOrUnjoin'])->name('event.join');
        Route::post('/event/add/comment/{id}', [CommentsController::class, 'addComment'])->name('comment.add');
        Route::post('/event/delete/comment/{id}', [CommentsController::class, 'deleteComment'])->name('comment.delete');
        Route::post('/event/deleteajax', [EventsController::class, 'deleteAjax'])->name('event.delete.ajax');
        Route::post('/event/delete/{id}', [EventsController::class, 'delete'])->name('event.delete');
        Route::post('/event/leave', [EventsController::class, 'leave'])->name('event.leave');
        Route::post('/event/remove/group', [EventsController::class, 'removeGroup'])->name('event.remove.group');
        Route::post('/event/remove/user', [EventsController::class, 'removeUser'])->name('event.remove.user');
        Route::post('/event/add/user', [EventsController::class, 'addUser'])->name('event.add.user');
        Route::post('/event/add/group', [EventsController::class, 'addGroup'])->name('event.add.group');
        Route::post('/event/search/usersandgroups', [EventsController::class, 'searchUsersGroups'])->name('event.search.usersAndGroups');

        Route::get('/groups', [GroupController::class, 'index'])->name('group.index');
        Route::get('/group/view/{id}', [GroupController::class, 'view'])->name('group.view');
        Route::get('/group/create', [GroupController::class, 'edit'])->name('group.create');
        Route::get('/group/edit/{id}', [GroupController::class, 'edit'])->name('group.edit');
        Route::post('/group/leave/{id}', [GroupController::class, 'leave'])->name('group.leave');
        Route::post('/group/store/{id}', [GroupController::class, 'store'])->name('group.store');
        Route::post('/group/deleteajax', [GroupController::class, 'deleteAjax'])->name('group.delete.ajax');
        Route::post('/group/delete/{id}', [GroupController::class, 'delete'])->name('group.delete');
        Route::post('/group/block', [GroupController::class, 'block'])->name('group.block');
        Route::post('/group/remove/user', [GroupController::class, 'removeUser'])->name('group.remove.user');
        Route::post('/group/search/usersandgroups', [GroupController::class, 'searchUsers'])->name('group.search.users');
        Route::post('/group/add/user', [GroupController::class, 'addUser'])->name('group.add.user');

        Route::get('/user/view/{id}', [UserController::class, 'view'])->name('user.view');
        Route::get('/users', [UserController::class, 'index'])->name('user.index');
        Route::get('/user/self', [UserController::class, 'userSelfProfile'])->name('user.self.profile');
        Route::get('/user/edit/{id}', [UserController::class, 'edit'])->name('user.edit');
        Route::post('/user/search', [UserController::class, 'search'])->name('user.search');
        Route::post('/user/delete/{id}', [UserController::class, 'delete'])->name('user.delete');
        Route::post('/user/block', [UserController::class, 'block'])->name('user.block');
        Route::post('/user/store/{id}', [UserController::class, 'store'])->name('user.store');

        Route::get('/calendar/view', [CalendarController::class, 'view'])->name('calendar.view');
        Route::get('/calendar/view/next', [CalendarController::class, 'viewNextMonth'])->name('calendar.view.next');
        Route::get('/calendar/view/prev', [CalendarController::class, 'viewPrevMonth'])->name('calendar.view.prev');

        Route::post('/ckeupload', [UploadController::class, 'CKEUpload'])->name('CKEUpload');
        Route::post('/ajaxupload', [UploadController::class, 'ajaxUpload'])->name('ajaxUpload');


        Route::get('/webex/auth', [WebexAuthController::class, 'redirectToWebexAuth'])->name('webex.auth');
        Route::get('/webex/callback', [WebexAuthController::class, 'handleCallback'])->name('webex.callback');

    });
    Route::post('/language/{valoda}', [LanguageController::class, 'setLanguage'])->name('setLanguage');


    Route::get('/error', [ErrorController::class, 'showError'])->name('error');

    //Legālās lapas
    Route::view('/privacy-policy', 'legal/privacy-policy');
    Route::view('/data-deletion', 'legal/data-deletion');
    Route::view('/terms-of-service', 'legal/terms-of-service');
});

app/View/Components/NavigationLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class NavigationLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public $navLinks=[];
    public function __construct()
    {
        if (auth()->user()!=null)
        {
            array_push($this->navLinks, [
                'href' => route('home'),
                'active' => request()->routeIs('home'),
                'text' => t('Upcoming events'),
            ]);
            array_push($this->navLinks, [
                'href' => route('calendar.view'),
                'active' => request()->routeIs('calendar.view'),
                'text' => t('Calendar'),
            ]);
            array_push($this->navLinks, [
                'href' => route('group.index'),
                'active' => request()->routeIs('group.index'),
                'text' => t('My groups'),
            ]);
            array_push($this->navLinks, [
                'href' => route('user.index'),
                'active' => request()->routeIs('user.index'),
                'text' => t('Users'),
            ]);
            array_push($this->navLinks, [
                'href' => route('event.all'),
                'active' => request()->routeIs('event.all'),
                'text' => t('All my events'),
            ]);
        }
        else
        {
            array_push($this->navLinks, [
                'href' => route('login'),
                'active' => request()->routeIs('login'),
                'text' => t('Log in'),
            ]);
            array_push($this->navLinks, [
                'href' => route('register'),
                'active' => request()->routeIs('register'),
                'text' => t('Register'),
            ]);
        }
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        $navLinks=$this->navLinks;
        return view('layouts.navigation', compact(['navLinks']));
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        
        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!--JQuery-->
        <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        

    </head>
    <body class="font-sans antialiased">
        <div id="app" class="min-h-screen bg-gray-100">
            <x-navigation-layout />

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <!--JQuery-->
        <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('home') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links for logged in user-->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                @foreach ($navLinks as $navLink)
                    <x-nav-link :href="$navLink['href']" :active="$navLink['active']">
                        {{ $navLink['text'] }}
                    </x-nav-link>
                @endforeach
                </div>

            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <div class="hidden sm:flex sm:items-center sm:ml-6 pr-2">
                    <form method="POST" action="{{route('setLanguage', ['valoda' => 'lv'])}}">
                        @csrf
                        <x-nav-link-submit :active="session('locale')=='lv'">
                            {{ t('LV') }}
                        </x-nav-link-submit>
                    </form>
                    <form method="POST" action="{{route('setLanguage', ['valoda' => 'en'])}}">
                        @csrf
                        <x-nav-link-submit :active="session('locale')=='en'">
                            {{ t('EN') }}
                        </x-nav-link-submit>
                    </form>
                </div>
                @if(Auth::user()!=NULL)
                <x-dropdown width="48">
                    <x-slot name="trigger">
                        <button
                            class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()?->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg"
                                    viewBox="0 0 20 20">
                                    <path fill-rule="evenodd"
                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                        clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <x-responsive-nav-link :href="route('user.self.profile')" :active="request()->routeIs('user.self.profile')">
                            {{ t('View my profile') }}
                        </x-responsive-nav-link>
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')" onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ t('Log out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
                @endif
            </div>


            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open"
                    class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex"
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round"
                            stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            @foreach ($navLinks as $navLink)
                <x-responsive-nav-link  :href="$navLink['href']" :active="$navLink['active']">
                    {{ $navLink['text'] }}
                </x-responsive-nav-link>
            @endforeach

        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()?->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()?->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <x-responsive-nav-link :href="route('user.self.profile')" :active="request()->routeIs('user.self.profile')">
                    {{ t('View my profile') }}
                </x-responsive-nav-link>
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')" onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ t('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>